elasticsearch:
  regex: "elasticsearch"
  image: "taskrabbit/elasticsearch-dump:latest"
  commands:
    - "rm -rf %target_dir%/*.json"
    - "elasticdump --input=http://%ip%:9200/ --output=%target_dir%/dump_mapping.json --type=mapping"
    - "elasticdump --input=http://%ip%:9200/ --output=%target_dir%/dump_data.json --type=data'"
  entrypoint: "sh -c"
