mysql:
  regex: "mysql"
  image: "mysql:latest"
  commands:
    - "sh -c 'mysqldump -h %ip% -u %env_MYSQL_USER% %env_MYSQL_DATABASE% > %target_dir%/%env_MYSQL_DATABASE%.dump'"
  environments:
    - MYSQL_PWD:%env_MYSQL_PASSWORD%
