mysql-root:
  regex: "mysql"
  image: "mysql:latest"
  commands:
    - "sh -c 'mysqldump -h %ip% -u root %env_MYSQL_DATABASE% > %target_dir%/%env_MYSQL_DATABASE%.dump'"
  environment:
    - MYSQL_PWD:%env_MYSQL_ROOT_PASSWORD%
